### ISSUE TITLE
Crafting Recipes

### ISSUE THREAD

**Issue by RustinFerris** [CitadelCore/DescentPacks#104]
- new recipe for Ancient stone/ancient rock + recipes for related blocks
- please remove Cryotheum dust from pure Certus quartz seed 
- set recipe for Eldritch Stone back to original (1 vis crystal surrounded by void stone)
- recipes for missing Curiosity types (Arcane, Ancient, Eldritch, Illuminating, Twisted)

**Comment by skyem123** [comment]
For the new recipes, what would you suggest?

**Comment by RustinFerris** [comment]
Ancient Rock: cobblestone surrounding any vis crystal 
Ancient Stone: Ancient Rock surrounding any vis crystal
a Curiosity: 1 book/Bookshelf Surrounded by corresponding vis crystal: (Arcane := Ordo; Ancient := Mortuus; Eldritch := Alienis; Illuminating := Lux; Twisted := Perditio)

**Comment by skyem123** [comment]
- [x] Ancient Rock
- [x] Ancient Stone
- [ ] Curiosities
- [ ] Eldritch Stone
- [ ] pure Certus quartz seed

**Comment by RustinFerris** [comment]
Arcane := Arcane Stone;
Ancient := Bone;
Eldritch := Eldritch Stone;
Illuminating := Torches/Glowstone Dust (either one)
Twisted := Nether Warts
