### ISSUE TITLE
AE2 Silicon Not Working

### ISSUE THREAD

**Issue by RustinFerris** [CitadelCore/DescentPacks#106]
Applied Energetics Silicon isn't working

**Comment by skyem123** [comment]
What do you mean by "Isn't Working"? You mean it cannot be crafted?

**Comment by RustinFerris** [comment]
It can't be used to make printed silicone

**Comment by CitadelCore** [comment]
It has no use. The ProjectRed silicon replaces it in all recipes.

**Comment by RustinFerris** [comment]
could we make a recipe to convert AE2 silicon to ProjectRed Silicon then?

**Comment by skyem123** [comment]
So you're saying you can make AE2 silicon but cannot use it?

**Comment by RustinFerris** [comment]
Yes

**Comment by skyem123** [comment]
Okay, then what we need to do is disable the AE2 silicon and make it convertible to ProjectRed silicon...
