### ISSUE TITLE
Purified water bottles stack, water bottles don't

### ISSUE THREAD

**Issue by deseven** [CitadelCore/DescentPacks#11]

**Comment by skyem123** [comment]
Bottle stacking seems to be completely broken at the moment. Since we removed the need to drink water it is less of a problem, but it's still annoying.

The question is... should water stack or not, now that no one needs to drink water?

**Comment by CitadelCore** [comment]
I think stacking is less important now that we have disabled Tough as Nails.

**Comment by deseven** [comment]
Nobody cared about this for half a year and now we're discussing it, really? I'm just going to close it.

**Comment by skyem123** [comment]
I found some time to maintain the pack so I decided to go through all open issues to see what I could improve now that I think I've got updates working.
