### ISSUE TITLE
device frame has same expensive recipie as machine frame

### ISSUE THREAD

**Issue by Raeffi** [CitadelCore/DescentPacks#19]
the whole point of the device frame being an item is so devices (that dont use power) can be cheap and easy to make

**Comment by skyem123** [comment]
This also has the side effect of making device frames impossible to craft.

**Comment by skyem123** [comment]
I've made things a bit easier to craft for device frames, so they now only require normal glass rather than hardened glass. I am open to tweaking this more, though.

**Comment by skyem123** [comment]
I'm adding this to the 1.1 milestone because I really want to know if this is truly fixed before I add more stuff.
