### ISSUE TITLE
biome terraforming block

### ISSUE THREAD

**Issue by Raeffi** [CitadelCore/DescentPacks#21]
we need some sort of machine that allows you to change the biome of an area using energy

**Comment by skyem123** [comment]
After some research it seems that "Extra Utilities 2" has a terraforming block.
So I will get working on adding it and integrating it (slowly)... so unfortunately #24 (Update 1.0.7) will not add this, like I planned.

**Comment by skyem123** [comment]
Alright, I'm working on #28 which should close this issue once it's done.

**Comment by skyem123** [comment]
Will be added after #31 is merged
