### ISSUE TITLE
Machine frame uses wrong kind of hardened glass

### ISSUE THREAD

**Issue by skyem123** [CitadelCore/DescentPacks#33]

**Comment by CitadelCore** [comment]
What kind should it be?

**Comment by skyem123** [comment]
Any kind. for some reason the recipe uses steel hardened glass only.

**Comment by CitadelCore** [comment]
Well, the original intention was to gate it behind steel... but it probably doesn't matter much now.

**Comment by skyem123** [comment]
Should I just change it to use any kind of hardened glass?

**Comment by CitadelCore** [comment]
That would be fine
