### ISSUE TITLE
Railcraft ores have not generated at all

### ISSUE THREAD

**Issue by skyem123** [CitadelCore/DescentPacks#42]
Zinc is apparently not generated in the world, so stuff brass cannot be made, so electric railcraft stuff is uncraftable.

**Comment by CitadelCore** [comment]
Can we force regeneration of specific chunks?

**Comment by skyem123** [comment]
That should be possible, but I am not sure what the best way to do it would be.

**Comment by skyem123** [comment]
COFH world has an ore (re)generation feature?

**Comment by skyem123** [comment]
@ThePiGuy24 has looked trough the railcraft config and apparently they only generate in certain biomes

**Comment by CitadelCore** [comment]
Well... that's going to be an issue... :ohgodno:

**Comment by skyem123** [comment]
Here's a possible workaround, we could install a mod that adds ores to the nether since the nether chunks aren't pre generated like the overworld is.

**Comment by CitadelCore** [comment]
Zinc generates outside of Frozen Hell.

**Comment by skyem123** [comment]
Is there any way to enable retrogeneration for zinc?

**Comment by skyem123** [comment]
I have enabled Zinc retro-generation. We will see how this plays out...
Also we need to work out why Zinc isn't being picked up by the mining laser...

**Comment by skyem123** [comment]
https://docs.blamejared.com/1.12/en/Mods/Industrial_Foregoing/LaserDrill/ Maybe we should add in missing ores using this?

**Comment by skyem123** [comment]
I added in missing ores, and enabled retrogen a while ago.
It's probably fixed as much as we could fix it...
