### ISSUE TITLE
Install inventorytweaks on the server as well

### ISSUE THREAD

**Issue by skyem123** [CitadelCore/DescentPacks#76]
The current config has it being client side only.
It works, but there is server code in inventory tweaks so it is not a pure client side only mod!
Since everyone has inventory tweaks, it should be installed on the server.

**Comment by CitadelCore** [comment]
What does the server side code actually do?
Also, is this meant to have "good first issue?" :slightly_smiling_face:

**Comment by skyem123** [comment]
I can't tell exactly, but it seems to tell the server when an inventory is being sorted.

It's a good first issue because it's literally a two line change.
