### ISSUE TITLE
add buildcraft

### ISSUE THREAD

**Issue by Raeffi** [CitadelCore/DescentPacks#77]
buildcraft has many machines that use energy and do useful building stuff for you

also quarries can be rebalanced to not be op

**Comment by skyem123** [comment]
It might be possible to use buildcraft to plug the missing gaps in mods...
We'd have to balance it and add recipies though...

**Comment by ThePiGuy24** [comment]
quarries dont seem that op to me as they remove blocks whereas lasers just generate ores out of thin air.

**Comment by CitadelCore** [comment]
leaving this out for now, will review at a later date
