### ISSUE TITLE
FTB Utilities is kinda broken for our usecase

### ISSUE THREAD

**Issue by skyem123** [CitadelCore/DescentPacks#95]
Here are some issues we've encountered, other than #92.

* The admin commands don't work. This will be a problem in the case of a misconfigured faction.
* The ability for factions to disable interaction with stuff and block placing and breaking etc will almost certainly cause issues for shared resources (such as the railway) and also goes against the spirit of the server.

**Comment by ThePiGuy24** [comment]
And its original purpose on this server, which was chunkloading, is "inconsistent" at best.
The block protection is real sucky though, especially because it can't be disabled in config.

**Comment by skyem123** [comment]
Maybe we should modify this mod and remove block protection while keeping chunk loading?
