### ISSUE TITLE
Some recipies are broken

### ISSUE THREAD

**Issue by skyem123** [CitadelCore/DescentPacks#96]
Due to the removal of a mod, some recipes are broken.
I do not know what broke, exactly, but I know IE blast furnace bricks broke for sure.
This was because it uses an ore dictionary name for something with no alternatives from other mods.

**Comment by CitadelCore** [comment]
Clearly no longer an emergency.

**Comment by CitadelCore** [comment]
Can we re-review this?

**Comment by skyem123** [comment]
Part of the problem is that we don't know which recipes are actually broken.
